drop table product;
drop table customer;
drop table order_info;
drop table order_line;

CREATE TABLE PRODUCT(
	prod_no VARCHAR2(5),
	prod_name VARCHAR2(30) NOT NULL,
	prod_price NUMBER(6),
	prod_info VARCHAR2(100),
	prod_mfd DATE
);

ALTER TABLE product
ADD CONSTRAINT prod_no_pk PRIMARY KEY(prod_no);
ALTER TABLE product
ADD CONSTRAINT prod_price_ck CHECK (prod_price>= 0);

CREATE TABLE CUSTOMER(
	ID VARCHAR2(5),
	PWD VARCHAR2(5) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(30),
	STATUS NUMBER(1)
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_id_pk PRIMARY KEY(ID);
ALTER TABLE customer
ADD CONSTRAINT customer_st_ck CHECK( STATUS IN (0, 1));

CREATE TABLE ORDER_INFO(
	ORDER_NO NUMBER,
	ORDER_ID VARCHAR2(5) NOT NULL,
	ORDER_DT DATE NOT NULL
);

ALTER TABLE ORDER_INFO
ADD CONSTRAINT info_no_pk PRIMARY KEY(ORDER_NO);
ALTER TABLE ORDER_INFO
ADD CONSTRAINT info_id_fk foreign key(ORDER_ID) REFERENCES CUSTOMER(ID);

CREATE TABLE ORDER_LINE(
	ORDER_NO NUMBER,
	ORDER_PROD_NO VARCHAR2(5),
	ORDER_QUANTITY NUMBER(3) NOT NULL
);

ALTER TABLE ORDER_LINE
ADD CONSTRAINT line_quantity_ck CHECK(ORDER_QUANTITY >= 1);
ALTER TABLE ORDER_LINE
ADD CONSTRAINT line_no_pk PRIMARY KEY(ORDER_NO, ORDER_PROD_NO);
ALTER TABLE ORDER_LINE
ADD CONSTRAINT line_no_fk FOREIGN KEY(ORDER_NO) REFERENCES ORDER_INFO(ORDER_NO);
ALTER TABLE ORDER_LINE
ADD CONSTRAINT line_prodno_fk FOREIGN KEY(ORDER_PROD_NO) REFERENCES PRODUCT(PROD_NO);